export const gameModeDict = {
  csc: {
    name: 'Conversation Starter Cards',
    description: 'Dive into fascinating questions, fun challenges, and engaging prompts generated by ChatGPT. Ignite connections and make every chat memorable!',
    shortDescription: 'Elevate your conversations with AI!',
    imgPath: 'csc.jpg',
    landing: () => import('./csc/CSCLanding'),
    create: () => import('./csc/CSCCreate'),
    room: () => import('./csc/CSCRoom'),
    bgColor: 'bg-jr'
  },
  bb: {
    name: 'Burning Bridges',
    description: "Burning Bridges is an activity that stirs up lively conversations with AI prompts that might even challenge friendships. Dive in and see if your bonds can withstand the heat!",
    shortDescription: 'Test your friendships with AI!',
    imgPath: 'csc.jpg',
    landing: () => import('./bb/BBLanding'),
    create: () => import('./bb/BBCreate'),
    room: () => import('./bb/BBRoom'),
    bgColor: 'bg-ns'
  },
  // bingo: {
  //   name: "Social Bingo",
  //   description: "Social Bingo puts your social skills to the test! Our app provides intriguing descriptions of fellow players, and it's your challenge to identify them. Just give us some fun facts about yourself, and the AI will create fun and exciting descriptions!",
  //   shortDescription: "Guess who matches the descriptions!",
  //   imgPath: 'csc.jpg',
  //   landing: () => import('./bingo/BingoLanding'),
  //   room: () => import('./bingo/BingoCreate'),
  //   create: () => import('./bingo/BingoRoom'),
  //   bgColor: 'bg-ne'
  // }
};

export const gameModeList = Object.entries(gameModeDict).map(([k, v]) => ({...v, abbr: k}));