export const gameModeDict = {
  csc: {
    name: 'Conversation Starter Cards',
    description: 'Dive into fascinating questions, fun challenges, and engaging prompts generated by ChatGPT. Ignite connections and make every chat memorable!',
    shortDescription: 'Elevate your conversations with AI!',
    instructions: 'Take turns reading out and share your experiences about the prompt given on the card. Feel free to keep it lighthearted and fun, and encourage open and honest sharing!',
    createInstructions: "Based on how you answer these questions, we'll ask ChatGPT to craft an ice-breaker game for you! So feel free to be as detailed as possible! ",
    imgPath: 'csc.jpg',
    landing: () => import('./csc/CSCLanding'),
    create: () => import('./csc/CSCCreate'),
    room: () => import('./csc/CSCRoom'),
    bgColor: 'bg-jr'
  },
  bb: {
    name: 'Burning Bridges',
    description: "Burning Bridges is an activity that stirs up lively conversations with AI prompts that might even challenge friendships. Dive in and see if your bonds can withstand the heat!",
    shortDescription: 'Test your friendships with AI!',
    instructions: "A single phone is passed around among players for their turns. They can press and hold a button to reveal the card's description secretly, then point to the person who fits the description and play scissors-paper-stone. If they lose, they must reveal the description to everyone. Afterward, they press the 'next person' button and pass the phone to the next player, continuing the game.",
    createInstructions: "Based on how you answer these questions, we'll ask ChatGPT to craft an ice-breaker game for you! So feel free to be as detailed as possible!",
    imgPath: 'csc.jpg',
    landing: () => import('./bb/BBLanding'),
    create: () => import('./bb/BBCreate'),
    room: () => import('./bb/BBRoom'),
    bgColor: 'bg-ns'
  },
  quiz: {
    name: 'QuizTopher',
    description: "Burning Bridges is an activity that stirs up lively conversations with AI prompts that might even challenge friendships. Dive in and see if your bonds can withstand the heat!",
    shortDescription: 'Test your friendships with AI!',
    instructions: "A single phone is passed around among players for their turns. They can press and hold a button to reveal the card's description secretly, then point to the person who fits the description and play scissors-paper-stone. If they lose, they must reveal the description to everyone. Afterward, they press the 'next person' button and pass the phone to the next player, continuing the game.",
    createInstructions: "Based on how you answer these questions, we'll ask ChatGPT to craft an ice-breaker game for you! So feel free to be as detailed as possible!",
    imgPath: 'csc.jpg',
    landing: () => import('./quiz/QuizLanding'),
    create: () => import('./quiz/QuizCreate'),
    room: () => import('./quiz/QuizRoom'),
    bgColor: 'bg-ne'
  }
};

export const gameModeList = Object.entries(gameModeDict).map(([k, v]) => ({...v, abbr: k}));