import CSCLanding from './csc/CSCLanding';
import CSCCreate from './csc/CSCCreate';
import CSCRoom from './csc/CSCRoom';
import BBLanding from './bb/BBLanding';
import BBRoom from './bb/BBRoom';

export const gameModeDict = {
  csc: {
    name: 'Conversation Starter Cards',
    description: 'Dive into fascinating questions, fun challenges, and engaging prompts generated by ChatGPT. Ignite connections and make every chat memorable!',
    shortDescription: 'Elevate your conversations with AI!',
    instructions: 'Take turns reading out and share your experiences about the prompt given on the card. Feel free to keep it lighthearted and fun, and encourage open and honest sharing!',
    createInstructions: "Based on how you answer these questions, we'll ask ChatGPT to craft an ice-breaker game for you! So feel free to be as detailed as possible! ",
    imgPath: 'csc.jpg',
    landing: CSCLanding,
    create: CSCCreate,
    room: CSCRoom,
    bgColor: 'bg-jr'
  },
  bb: {
    name: 'Burning Bridges',
    description: "Burning Bridges is an activity that stirs up lively conversations with AI prompts that might even challenge friendships. Dive in and see if your bonds can withstand the heat!",
    shortDescription: 'Test your friendships with AI!',
    instructions: "Playing 'Burning Bridges' is a breeze! Just pick an AI-generated prompt, share your thoughts on it, and engage in open conversations. Remember, it's all in good fun, even if it tests your friendships!",
    createInstructions: "Creating your game is easy! Just define the purpose, describe your group, and specify participant familiarity. We'll craft a tailored icebreaker for your unique needs!",
    imgPath: 'csc.jpg',
    landing: BBLanding,
    room: BBRoom,
    bgColor: 'bg-ns'
  }
};

export const gameModeList = Object.entries(gameModeDict).map(([k, v]) => ({...v, abbr: k}));