<!-- /csc/create -->

<template>
  <div class="h-screen bg-jr">
    <NavBar backLink="/csc" text="Conversation Starter Cards" ref="nav"/>
    <section id='browse-game-modes' class="px-10 py-10 rounded-t-3xl bg-lrt-background grid gap-5 place-content-center min-h-[84%]">
      <h1 class="font-bold text-3xl text-jr">Create Game</h1>
      <span class="max-w-3xl">{{ createInstructions }}</span>

      <form class="bg-light shadow-md rounded-lg px-8 pt-6 pb-8 mb-4">
        <ContextForm ref="context"/>
        <CSCForm ref="csc"/>
        <br/>
        <OrangeButton :onClick="generateQuestions" text="Generate Questions" class="mt-5"/>
      </form>
      
      <QuestionForm ref="questions"/>

      <OrangeButton :onClick="createRoom" text="Create Room"/>
    </section>
  </div>
</template>

<script>
import { useMeta } from 'vue-meta';
import axios from 'axios';
import NavBar from '@/components/NavBar.vue';
import { gameModeDict } from '../gameModes';
import { getHeader, getUrl } from '@/services';
import ContextForm from '@/components/ContextForm.vue';
import CSCForm from '@/components/csc/CSCForm.vue';
import OrangeButton from '@/components/buttons/OrangeButton.vue';
import loginToGoogle from '@/components/loginToGoogle';
import QuestionForm from '@/components/csc/QuestionForm.vue';

export default {
  name: 'CSCCreate',
  setup() {
    useMeta({
      title: 'Conversation Starter Cards',
      description: 'Dive into fascinating questions, fun challenges, and engaging prompts generated by ChatGPT. Ignite connections and make every chat memorable!'
    })
  },
  data() {
    return {
      createInstructions: gameModeDict.csc.createInstructions,
    };
  },
  components: { NavBar, ContextForm, CSCForm, OrangeButton, QuestionForm },
  created() {
    if (localStorage.getItem('expiry') < Date.now()) {
      this.$router.push('/csc');
      this.$swal.fire({
        icon: 'warning',
        title: 'Please log in to Google to create a game!',
        showCancelButton: true,
        confirmButtonText: 'Log In'
      }).then(result => {
        if (result.isDismissed) {
          return;
        }
        loginToGoogle({ redirect: '/csc/create', router: this.$router });
      });
    }
  },
  mounted() {
    this.populate({ url: getUrl('csc/context') });
  },
  methods: {
    async populate({ url }) {
      const headers = getHeader();
      axios.get(url, { headers })
        .then(response => {
          switch (response.status) {
            case 200:
            case 201:
              return response.data;
            default:
              return;
          }
        })
        .then(data => {
          if (!data) return;
          this.$refs.context.setValues(data.baseContext);
          this.$refs.csc.setValues(data.cscContext);
          this.$refs.questions.setValues(data.questions);
        })
        .catch(err => {
          console.log(err);
        });
    },
    async generateQuestions() {
      const payload = {
        baseContext: this.$refs.context.getValues(),
        cscContext: this.$refs.csc.getValues()
      };
      const url = getUrl('csc/questions/generate');
      const headers = getHeader();
      axios.post(url, payload, { headers })
        .then(response => {
          switch (response.status) {
            case 200:
            case 201:
              return response.data;
            default:
              throw new Error(response?.message ?? 'Bad method!');
          }
        })
        .then(data => {
          this.$refs.questions.setValues(data.questions);
        })
        .catch(err => {
          this.$swal.fire('Oops...', `Generate questions failed! ${err?.response?.data?.message ?? ""}`, 'error');
          // this.$refs.questions.setValues({ questions: [{ id: 12345, text: "Who are you" }, { id: 12345, text: "Who are you" }] })
        })
    },
    async createRoom() {
      const url = getUrl('room/csc/create');
      const headers = getHeader();
      axios.post(url, {}, { headers })
        .then(response => {
          switch (response.status) {
            case 200:
            case 201:
              return response.data;
            default:
              throw new Error(response?.message ?? 'Bad method!');
          }
        })
        .then(data => {
          this.$router.push(`${data.id}`);
        })
        .catch(err => {
          this.$swal.fire({
            icon: 'error',
            title: 'Oops...',
            text: `Something went wrong when creating your room! ${err?.response?.data?.message ?? ""}`
          });
        });
    }
  }
}
</script>
