<!-- /csc -->

<template>
  <div class="h-screen bg-gradient-to-b from-jr-light via-jr to-jr-dark z-0">
    <NavBar backLink="/browse" text="Conversation Starter Cards"/>

    <section class="min-h-[76%] w-screen z-10 grid place-content-center">
      <div class="bg-light rounded-3xl max-w-lg p-5 z-10 grid gap-5 m-5">
        <h1 class="text-3xl font-bold text-jr">How to Play</h1>
        <ol>
          <li><b class="text-jr">Step 1</b>. Have someone <router-link to="csc/create" class="text-jr underline hover:text-jr-light">create a game</router-link>.</li>
          <li><b class="text-jr">Step 2</b>. Join the game on any device, preferably a phone.</li>
          <li><b class="text-jr">Step 3</b>. Pick a topic to talk about and share your experiences. Feel free to keep it lightheated and fun, and encourage open and honest sharing!</li>
        </ol>
      </div>
      <PINInput/>
    </section>

    <div class="background-circle-csc bg-jr-v-light"></div>
    <div class="background-diamond-csc bg-jr-v-light"></div>
  </div>
</template>

<script>
import { useMeta } from 'vue-meta';
import NavBar from '@/components/NavBar.vue';
import { gameModeDict } from '../gameModes';
import PINInput from '@/components/inputs/PINInput.vue';

export default {
  name: 'CSCLanding',
  setup() {
    useMeta({
      title: 'Conversation Starter Cards',
      description: 'Dive into fascinating questions, fun challenges, and engaging prompts generated by ChatGPT. Ignite connections and make every chat memorable!'
    })
  },
  data() {
    return {
      instructions: gameModeDict.csc.instructions,
      imgPath: gameModeDict.csc.imgPath,
    }
  },
  components: {
    NavBar,
    PINInput,
}
}
</script>

<style scoped>
.background-circle-csc {
  position: absolute;
  top: 65%;
  left: 100%;
  transform: translate(-100%, -50%);
  width: 30vh; /* Adjust the size of the circle as needed */
  height: 60vh; /* The width and height should be equal for a circle */
  border-top-left-radius: 60vh;
  border-bottom-left-radius: 60vh;
  z-index: 0; /* Place the circle behind other content */
  opacity: 20%;
}

.background-diamond-csc {
  position: absolute;
  top: 20%;
  left: 0%;
  transform: translate(-50%, -50%) rotate(45deg);
  width: 50vmax; /* Adjust the size of the circle as needed */
  height: 50vmax; /* The width and height should be equal for a circle */
  border-radius: 4rem; /* Creates a circle by setting border-radius to 50% */
  z-index: 0; /* Place the circle behind other content */
  opacity: 20%;
}
</style>
