<!-- /quiz/create -->

<template>
  <div class="h-screen bg-ne">
    <NavBar backLink="/quiz" text="Conversation Starter Cards" ref="nav"/>
    <section id='browse-game-modes' class="px-10 py-10 rounded-t-3xl bg-lrt-background grid gap-5 place-content-center min-h-[84%]">
      <h1 class="font-bold text-3xl text-ne">Create Game</h1>
      <span class="max-w-3xl">{{ createInstructions }}</span>

      <form class="bg-light shadow-md rounded-lg px-8 pt-6 pb-8 mb-4">
        <ContextForm ref="context"/>
        <QuizForm ref="quiz"/>
      </form>

      <OrangeButton :onClick="createRoom" text="Create Room"/>
    </section>
  </div>
</template>

<script>
import { useMeta } from 'vue-meta';
import axios from 'axios';
import NavBar from '@/components/NavBar.vue';
import { gameModeDict } from '../gameModes';
import { getHeader, getUrl } from '@/services';
import ContextForm from '@/components/ContextForm.vue';
import QuizForm from '@/components/quiz/QuizForm.vue';
import OrangeButton from '@/components/buttons/OrangeButton.vue';
import loginToGoogle from '@/components/loginToGoogle';

export default {
  name: 'QuizCreate',
  setup() {
    useMeta({
      title: 'Conversation Starter Cards',
      description: 'Dive into fascinating questions, fun challenges, and engaging prompts generated by ChatGPT. Ignite connections and make every chat memorable!'
    })
  },
  data() {
    return {
      createInstructions: gameModeDict.quiz.createInstructions,
    };
  },
  components: { NavBar, ContextForm, QuizForm, OrangeButton },
  created() {
    if (localStorage.getItem('expiry') < Date.now()) {
      this.$router.push('/quiz');
      this.$swal.fire({
        icon: 'warning',
        title: 'Please log in to Google to create a game!',
        showCancelButton: true,
        confirmButtonText: 'Log In'
      }).then(result => {
        if (result.isDismissed) {
          return;
        }
        loginToGoogle({ redirect: '/quiz/create', router: this.$router });
      });
    }
  },
  mounted() {
    this.populate({ url: getUrl('quiz/context') });
  },
  methods: {
    async populate({ url }) {
      const headers = getHeader();
      axios.get(url, { headers })
        .then(response => {
          switch (response.status) {
            case 200:
              return response.data;
            default:
              return;
          }
        })
        .then(data => {
          if (!data) return;
          this.$refs.context.setValues(data.baseContext);
          this.$refs.quiz.setValues(data.quizContext);
        })
        .catch(err => {
          console.log(err);
        });
    },
    async createRoom() {
      const url = getUrl('room/quiz/create');
      const headers = getHeader();
      axios.post(url, {}, { headers })
        .then(response => {
          switch (response.status) {
            case 201:
              return response.data;
            default:
              throw new Error('Bad method!');
          }
        })
        .then(data => {
          this.$router.push(`${data.id}`);
        })
        .catch(err => {
          console.log(err);
          this.$swal.fire({
            icon: 'error',
            title: 'Oops...',
            text: 'Something went wrong when creating your room!'
          });
        });
    }
  }
}
</script>
